-- MySQL Script generated by MySQL Workbench
-- Tue Apr 16 10:54:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


CREATE SCHEMA IF NOT EXISTS `lab2` ;
USE `lab2` ;

-- -----------------------------------------------------
-- Table `lab2`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `details` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab2`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`employees` (
  `id` INT NOT NULL auto_increment,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab2`.`contracts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`contracts` (
  `id` INT NOT NULL auto_increment,
  `date` DATE NULL,
  `clients_id` INT NOT NULL,
  `employees_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contracts_clients1_idx` (`clients_id` ASC) VISIBLE,
  INDEX `fk_contracts_employees1_idx` (`employees_id` ASC) VISIBLE,
  CONSTRAINT `fk_contracts_clients1`
    FOREIGN KEY (`clients_id`)
    REFERENCES `lab2`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contracts_employees1`
    FOREIGN KEY (`employees_id`)
    REFERENCES `lab2`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab2`.`order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`order_status` (
  `id` INT NOT NULL auto_increment,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab2`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`orders` (
  `id` INT NOT NULL auto_increment,
  `date_start` DATE NULL,
  `date_finish` DATE NULL,
  `contracts_id` INT NOT NULL,
  `employees_id` INT NOT NULL,
  `order_status_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_contracts1_idx` (`contracts_id` ASC) VISIBLE,
  INDEX `fk_orders_employees1_idx` (`employees_id` ASC) VISIBLE,
  INDEX `fk_orders_order_status1_idx` (`order_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_contracts1`
    FOREIGN KEY (`contracts_id`)
    REFERENCES `lab2`.`contracts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_employees1`
    FOREIGN KEY (`employees_id`)
    REFERENCES `lab2`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_order_status1`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `lab2`.`order_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab2`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`products` (
  `id` INT NOT NULL auto_increment,
  `vencode` INT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab2`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`suppliers` (
  `id` INT NOT NULL auto_increment,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab2`.`prices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`prices` (
  `id` INT NOT NULL auto_increment,
  `vencode` INT NULL,
  `name` VARCHAR(45) NULL,
  `price` INT NULL,
  `suppliers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_prices_suppliers1_idx` (`suppliers_id` ASC) VISIBLE,
  CONSTRAINT `fk_prices_suppliers1`
    FOREIGN KEY (`suppliers_id`)
    REFERENCES `lab2`.`suppliers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab2`.`vehicle_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`vehicle_type` (
  `id` INT NOT NULL auto_increment,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab2`.`delivery_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`delivery_status` (
  `id` INT NOT NULL auto_increment,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `lab2`.`transportation_sup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`transp_sup` (
  `id` INT NOT NULL auto_increment,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab2`.`deliveries`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `lab2`.`deliveries` (
  `id` INT NOT NULL,
  `date` DATETIME NULL,
  `transp_sup_id` INT NOT NULL,
  `vechicle_type_id` INT NOT NULL,
  `delivery_status_id` INT NOT NULL,
  PRIMARY KEY (`id`, `transp_sup_id`, `vechicle_type_id`, `delivery_status_id`),
  INDEX `fk_deliveries_transp_sup_idx` (`transp_sup_id` ASC) VISIBLE,
  INDEX `fk_deliveries_vechicle_type1_idx` (`vechicle_type_id` ASC) VISIBLE,
  INDEX `fk_deliveries_delivery_status1_idx` (`delivery_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_deliveries_transp_sup`
    FOREIGN KEY (`transp_sup_id`)
    REFERENCES `lab2`.`transp_sup` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_deliveries_vechicle_type1`
    FOREIGN KEY (`vechicle_type_id`)
    REFERENCES `lab2`.`vechicle_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_deliveries_delivery_status1`
    FOREIGN KEY (`delivery_status_id`)
    REFERENCES `lab2`.`delivery_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `lab2`.`application_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`application_type` (
  `id` INT NOT NULL auto_increment,
  `name` VARCHAR(45) NULL,
  `price` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab2`.`products_in_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`products_in_order` (
  `id` INT NOT NULL auto_increment,
  `orders_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  `application_type_id` INT NOT NULL,
  `deliveries_id` INT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_in_order_orders1_idx` (`orders_id` ASC) VISIBLE,
  INDEX `fk_products_in_order_products1_idx` (`products_id` ASC) VISIBLE,
  INDEX `fk_products_in_order_application_type1_idx` (`application_type_id` ASC) VISIBLE,
  INDEX `fk_products_in_order_deliveries1_idx` (`deliveries_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_in_order_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `lab2`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_in_order_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `lab2`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_in_order_application_type1`
    FOREIGN KEY (`application_type_id`)
    REFERENCES `lab2`.`application_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_in_order_deliveries1`
    FOREIGN KEY (`deliveries_id`)
    REFERENCES `lab2`.`deliveries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab2`.`deliveries_has_suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`deliveries_has_suppliers` (
  `deliveries_id` INT NOT NULL,
  `suppliers_id` INT NOT NULL,
  PRIMARY KEY (`deliveries_id`, `suppliers_id`),
  INDEX `fk_deliveries_has_suppliers_suppliers1_idx` (`suppliers_id` ASC) VISIBLE,
  INDEX `fk_deliveries_has_suppliers_deliveries1_idx` (`deliveries_id` ASC) VISIBLE,
  CONSTRAINT `fk_deliveries_has_suppliers_deliveries1`
    FOREIGN KEY (`deliveries_id`)
    REFERENCES `lab2`.`deliveries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_deliveries_has_suppliers_suppliers1`
    FOREIGN KEY (`suppliers_id`)
    REFERENCES `lab2`.`suppliers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;





-- -----------------------------------------------------
-- Table `lab2`.`vehicle_type_has_transportation_sup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`vech_tsup` (
  `vechicle_type_id` INT NOT NULL,
  `transp_sup_id` INT NOT NULL,
  `price` DECIMAL(10,2) NULL,
  PRIMARY KEY (`vechicle_type_id`, `transp_sup_id`),
  INDEX `fk_vech_tsup_transp_sup1_idx` (`transp_sup_id` ASC) VISIBLE,
  INDEX `fk_vech_tsup_vechicle_type1_idx` (`vechicle_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_vech_tsup_vechicle_type1`
    FOREIGN KEY (`vechicle_type_id`)
    REFERENCES `lab2`.`vechicle_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vech_tsup_transp_sup1`
    FOREIGN KEY (`transp_sup_id`)
    REFERENCES `lab2`.`transp_sup` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


